name: build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    # UTC 表記
    # 日本時間 23:30
    - cron: "30 14 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Register SSH key
      env:
        BOOSTJP_GITHUB_IO_SECRETS: ${{ secrets.BOOSTJP_GITHUB_IO_SECRETS }}
      run: |
        mkdir -p $HOME/.ssh
        echo "$BOOSTJP_GITHUB_IO_SECRETS" > $HOME/.ssh/id_ed25519
        chmod 600 $HOME/.ssh/id_ed25519

    # site_generator
    - uses: actions/checkout@v2
      with:
        repository: cpprefjp/site_generator
        path: site_generator
    - run: git submodule update --init
      working-directory: site_generator

    # boostjp.github.io
    - uses: actions/checkout@v2
      with:
        repository: boostjp/boostjp.github.io
        path: site_generator/boostjp/boostjp.github.io

    # site
    - uses: actions/checkout@v2
      with:
        repository: boostjp/site
        path: site_generator/boostjp/site
        # atom 生成のために全履歴が必要
        fetch-depth: 0
    - run: git submodule update --init
      working-directory: site_generator/boostjp/site

    # image
    - uses: actions/checkout@v2
      with:
        repository: boostjp/image
        path: site_generator/boostjp/image

    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: 3.11
        # 3.12でUndefined symbolエラーがでた

    # あとはスクリプトで頑張る
    - run: ./boostjp/site/.github/workflows/script/build.sh
      working-directory: site_generator

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
